CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(user_id)
);

CREATE TABLE jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    execution_date TIMESTAMP, 
    status VARCHAR(100), 
    message TEXT,
    user_id BIGINT, 
    PRIMARY KEY(job_id),
    CONSTRAINT fk_user
      FOREIGN KEY(user_id) 
	  REFERENCES users(user_id)
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    ean BIGINT,
    name TEXT,
    h1 TEXT,
    second_name VARCHAR(255),
    brand VARCHAR(255),
    author VARCHAR(255),
    other_category VARCHAR(255),
    main_category VARCHAR(255),
    attribute_categories VARCHAR(255),
    image_url TEXT,
    page_link VARCHAR(255),
    meta_title TEXT,
    meta_keywords TEXT,
    meta_description TEXT,
    description TEXT,
    canonical_link VARCHAR(255),
    no_index_flag BOOLEAN,
    isbn VARCHAR(255),
    job_id BIGINT,
    primary key (product_id),
    CONSTRAINT fk_job
      FOREIGN KEY(job_id) 
	  REFERENCES jobs(job_id)
);

INSERT INTO users (user_name, password, name) VALUES 
('user', '$2a$10$/zrMXTJU/lFxAyyXMSHyxuv7v93tLFJ8.9K3Cq83ClcBq4zszcU2O', 'Data User');